package main

class MyException(message: string, cause: Exception): Exception(message, cause)
class MeException(message: string, cause: Exception): Exception(message, cause)

fun main() {
	//throw MyException("my error", nil)
	try {
		foo()
	} catch (e: Exception) {
		println('Handler my')
		throw MyException('nested', nil)
	} catch (e: MeException) {
		println('Handler me')
	} finally {
		println('finally')
	}
}

fun foo() {
	throw MeException("my error", nil)
}


